name: Automação Harley Selenium

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install selenium tabulate smtplib email

      - name: Instalar Chrome e ChromeDriver
        run: |
          sudo apt-get install -y chromium-browser
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Executar o script
        run: python sodre_copart_chrome.py
